#!/usr/bin/env python3
"""1-async_comprehension module."""


from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    async_comprehension: Calls an aiter() of random float numbers \
        using async comprehension.

    Returns:
        List[float]: A list of float random numbers generated by an aiter() \
            asynchronously.
    """
    rand_nums: List[float] = [i async for i in async_generator()]

    return rand_nums
