#!/usr/bin/env python3
"""1-concurrent_coroutines."""


from typing import List
task_wait_random = __import__('3-tasks').task_wait_random


async def task_wait_n(n: int, max_delay: int) -> List[float]:
    """
    wait_n: A routine that calls another routine repeatedly.

    Args:
        n (int): number of times to call wait_random.
        max_delay (int): range of values generated by wait_random every time \
            it is called.

    Returns:
        List[float]: A list of sorted floats returned for every routine call.
    """
    delaysLst: list = list()
    for i in range(n):
        delaysLst.append((await task_wait_random(max_delay)))

    return sorted(delaysLst)
